{
 "title": "Range Degradation",
 "tags": [ "TeslamateCustomDashboards" ],
 "time": { "from": "now-6M", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "car_id",
    "label": "Car",
    "query": "SELECT name AS __text, id AS __value FROM cars ORDER BY display_priority ASC, name ASC"
   },
   {
    "name": "length_unit",
    "query": "SELECT unit_of_length FROM settings LIMIT 1"
   },
   {
    "name": "preferred_range",
    "query": "SELECT preferred_range FROM settings LIMIT 1"
   },
   {
    "name": "base_url",
    "query": "SELECT base_url FROM settings LIMIT 1"
   },
   { "name": "interval", "label": "Interval AVG", "query": "1d,7d,15d,30d " }
  ]
 },
 "panels": [
  {
   "title": "Range Degradation",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "SELECT        $__time(cp.start_date), \r\n              convert_km((cp.end_${preferred_range}_range_km / cp.end_battery_level * 100)::numeric,'$length_unit') AS \"range\",\r\n              convert_km(p.odometer::numeric,'$length_unit') AS \"Odometer [${length_unit}]\"\r\nFROM charging_processes cp\r\n  INNER JOIN positions p ON cp.position_id = p.id\r\nWHERE $__timeFilter(cp.start_date) and cp.car_id = $car_id\r\nand cp.duration_min > 10 \r\nORDER by cp.start_date\r\n"
    },
    {
     "rawSql": "SELECT  $__timeGroup(cp.start_date, $interval) AS time, \r\n        AVG(convert_km((cp.end_${preferred_range}_range_km / cp.end_battery_level * 100)::numeric,'$length_unit')) AS \"Max ${preferred_range} range ($interval avg) [${length_unit}]\"\r\nFROM charging_processes cp\r\nWHERE $__timeFilter(cp.start_date) and cp.car_id = $car_id\r\nand cp.duration_min > 10 \r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Trips (this period)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select ROUND(convert_km(sum(distance)::numeric, '$length_unit'),0)|| ' $length_unit' as \"Logged\"\r\nfrom drives \r\nwhere car_id = $car_id AND $__timeFilter(start_date)\r\n"
    },
    {
     "rawSql": "SELECT ROUND(convert_km((max(end_km) - min(start_km))::numeric, '$length_unit'),0)|| ' $length_unit' as \"Mileage\"\nFROM drives WHERE car_id = $car_id AND $__timeFilter(start_date)"
    },
    {
     "rawSql": "SELECT (\r\n (SELECT ROUND(convert_km((max(end_km) - min(start_km))::numeric, '$length_unit'),0) FROM drives WHERE car_id = $car_id AND $__timeFilter(start_date)) - \r\n (SELECT ROUND(convert_km(sum(distance)::numeric, '$length_unit'),0) from drives where car_id = $car_id AND $__timeFilter(start_date)) || ' $length_unit'\r\n)\r\nAS \"Data lost (not logged)\"\r\n"
    }
   ]
  },
  {
   "title": "Battery Stats (this period)",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n\tCOUNT(*) AS \"Total charges\"\r\nFROM\r\n\tcharging_processes\r\nWHERE\r\n\tcar_id = $car_id AND $__timeFilter(start_date) AND charge_energy_added > 0.01\r\n\t"
    },
    {
     "rawSql": "SELECT\n\tsum(charge_energy_added) as \"Total energy added\"\nFROM\n\tcharging_processes\nWHERE\n\tcar_id = $car_id AND $__timeFilter(start_date) AND charge_energy_added > 0.01"
    },
    {
     "rawSql": "SELECT\r\n\tSUM(charge_energy_used) AS \"Total energy used\"\r\nFROM\r\n\tcharging_processes\r\nWHERE\r\n\tcar_id = $car_id AND $__timeFilter(start_date) AND charge_energy_added > 0.01\r\n"
    },
    {
     "rawSql": "SELECT\r\n\tSUM(charge_energy_added) * 100 / SUM(charge_energy_used) AS \"Charge Efficiency\"\r\nFROM\r\n\tcharging_processes\r\nWHERE\r\n\tcar_id = $car_id AND $__timeFilter(start_date) AND charge_energy_added > 0.01\r\n"
    }
   ]
  }
 ]
}